# Generated by Django 3.0.2 on 2020-01-09 22:05

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_auto_20200109_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluated_on', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('levels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), size=4)),
            ],
        ),
        migrations.CreateModel(
            name='SkillEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skill_evaluations', to='evaluations.Evaluation')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skill_evaluations', to='evaluations.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('skills', models.ManyToManyField(related_name='_scheduledevaluation_skills_+', to='evaluations.Skill')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Team')),
            ],
        ),
        migrations.AddField(
            model_name='evaluation',
            name='scheduled_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluations.ScheduledEvaluation'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evalations', to=settings.AUTH_USER_MODEL),
        ),
    ]
