# Generated by Django 3.0.3 on 2020-02-28 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_remove_evaluation_evaluated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='scheduled_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='evaluations.ScheduledEvaluation'),
        ),
        migrations.AlterField(
            model_name='skillevaluation',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_evaluations', to='evaluations.Evaluation'),
        ),
    ]
