# Generated by Django 3.0.3 on 2020-03-03 15:40

from django.db import migrations


def set_skill_order(apps, schema_editor):
    Skill = apps.get_model('evaluations', 'Skill')
    order = 0
    for skill in Skill.objects.order_by('pk').all():
        order += 1
        skill.order = order
        skill.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0005_auto_20200303_1538'),
    ]

    operations = [migrations.RunPython(set_skill_order, noop)]
