# Generated by Django 3.2.2 on 2021-05-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0008_auto_20210507_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(blank=True, choices=[('fe', 'Front End'), ('be', 'Back End'), ('dt', 'Dev Tools'), ('ag', 'Agile Development'), ('ss', 'Soft Skills')], max_length=2, null=True),
        ),
    ]
