# Generated by Django 3.2.3 on 2021-05-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0009_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(blank=True, choices=[('fe', 'Front End'), ('be', 'Back End'), ('dt', 'Dev Tools'), ('ag', 'Agile Development'), ('ss', 'Soft Skills'), ('ge', 'General')], max_length=2, null=True),
        ),
    ]
