# Generated by Django 3.1 on 2021-05-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210507_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='skills_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
